spring:
  application:
    name: lovable


  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test?serverTimezone=Asia/Kolkata
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    openai:
      api-key:
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temperature: 0.0

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  api:
    secret: sk_test_51Ta8IfEExFVSixs0iUJrsLjpOJC43RUweBfzURwz9Dox3bfgODyYpexp7keKiWL3PISySfZ70bu5EmLI93aqZt6M00JgxhyXx3
  webhook:
    secret: whsec_fb277f2c5a5d42adddbd90b873d55a492673e74647322bb422b22ebde0df2d5d

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects